spring:
  profiles:
    active: dev
  datasource: #数据库默认公共配置
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #连接池的配置信息
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      max-idle: 200
      min-idle: 5
      initial-size: 5
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 10000
      default-auto-commit: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
  jackson: #自定义jackson解析时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null #空数据不反回
    serialization:
      indent-output: true #让控制器输出json字符串格式
  data: #redis公共配置
    redis:
      repositories:
        enabled: false #禁用redis的repositories
  output: #控制台彩色输出
    ansi:
      nabled: detect #检查终端是否支持ANSI，是的话就采用彩色输出
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
  freemarker:
    checkTemplateLocation: false

server: #Tomcat公共配置
  tomcat:
      accept-count: 1000000 #最大等待队列长度
      max-connections: 200000   #最大链接数
      max-threads: 300 #最大线程数
      min-spare-threads: 50 #最小线程数
      uri-encoding: UTF-8
      max-http-post-size: 100MB #请请求体最大长度kb
      accesslog:
        enabled: true
  port: 8080
  connection-timeout: 120000 #链接建立超时时间
  #servlet:
    #context-path: /zlgmces #访问根路径
  compression:
       enabled: true
  http2:
     enabled: true
logback: #logback日志输出配置
  configurationFile: logback-spring.xml #logback的配置文件名
mybatis-plus: #mybatis-plus配置
  configuration:
     map-underscore-to-camel-case: true
     use-generated-keys: true
  mapper-locations: classpath*:/mappers/**/*.xml
  type-handlers-package: com.config.DataSourceConfig
  #type-aliases-package: com.domain.entity
  #type-aliases-package作用
  #在Mybatis的mapper.xml文件中resultType的type或者paramterType会返回自定义entity，此时可以用全类名名来指定这些实体