spring:
  redis: #Redis数据源
    database: 0 #redis数据库索引，默认为0
    host: 10.10.101.189
    port: 16399
    timeout: 6000
    #password: 123456
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
sql1: #主数据库
  datasource:
    url: jdbc:mysql://localhost:3306/pulmonary_function1?useAffectedRows=true&useSSL=false&serverTimezone=UTC&&characterEncoding=UTF-8&&useUnicode=true&amp
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
zeroPoint: #校零值默认值
     initialValue: 789
dllName: #dll文件名
     algorithm: sp03.dll
     device: protocol.dll